config/routes.rb
Rails.application.routes.draw do

  root 'subjects#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  resources :pages do 
    member do
      get :delete
    end
  end

  resources :subjects do 
    member do 
      get :delete
    end
  end

  
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  match "demo/", :to => "demo#index", :via => :get
  
  

end

app/models/section.rb
class Section < ActiveRecord::Base
    belongs_to :page
    has_many :section_edits 
    has_many :admin_users, through: :section_edits
    
    scope :sorted, lambda { order("position ASC") }
    
    CONTENT_TYPES = ['text', 'HTML']
    
    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    validates_inclusion_of :content_type, :in => CONTENT_TYPES,
      :message => "must be one of #{CONTENT_TYPES.join(', ')}"
    validates_presence_of :content
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  layout 'admin'
  
  before_action :confirm_logged_in
  
  def index
    @page_title = "All Sections"
    @sections = Section.all
  end

  def new
    @section = Section.new()
    @section_count = Section.count + 1
    @pages = Page.sorted
  end
  
  def create
   @section = Section.new(section_params)
   if @section.save
     flash[:notice] = "Section saved successfully!"
     redirect_to(sections_path)
   else
     @section_count = Section.count + 1
     @pages = Page.sorted
     render("new")
   end
  end

  def show
    @section = Section.find(params[:id])
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.sorted
  end
  
  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice] = "Section updated successfully!"
      redirect_to(sections_path)
    else
      @section_count = Section.count
      @pages = Page.sorted
      render("edit")
    end
  end

  def delete
    @section = Section.find(params[:id])
  end
  
  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section deleted successfully!"
    redirect_to(sections_path)
  end
  
  private
  
  def section_params
    params.require(:section).permit(:name, :position, :visible, :content_type, :content, :page_id)
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Page ID</th>
        <td><%= f.select(:page_id, @pages.map { |p| [p.name, p.id] }) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@section_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
      <tr>
        <th>Content Type</th>
        <td>
          <%= f.radio_button(:content_type, 'text') %> Text
          <%= f.radio_button(:content_type, 'HTML') %> HTML
        </td>
      </tr>
      <tr>
        <th>Content</th>
        <td><%= f.text_area(:content, :size => '40x10') %></td>
      </tr>
    </table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Section</h2>

  <%= form_for(@section, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>

  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Edit Section</h2>

  <%= form_for (@section) do |f| %>

    <%= render(:partial => "form", :locals => {:f => f})%>
  
    <div class="form-buttons">
      <%= f.submit("Edit Section") %>
    </div>

  <% end %>
</div>

app/views/sections/index.html.erb
<div class="subjects index">
  <h2>Sections</h2>

  <%= link_to("Add New Section", new_section_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Visible</th>
      <th>Content Type</th>
      <th>Content</th>
      <th>Section Edits</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.name %></td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="center"><%= section.content_type %></td>
      <td class="center"><%= section.content %></td>
      <td class="center"><%= section.section_edits.name %></td>
      <td class="actions">
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Section</h2>

  <%= form_for (@section) do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>

  <% end %>
</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Section</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>
</div>