config/routes.rb
Rails.application.routes.draw do

  root 'subjects#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  resources :pages do 
    member do
      get :delete
    end
  end

  resources :subjects do 
    member do 
      get :delete
    end
  end

  
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  match "demo/", :to => "demo#index", :via => :get
  
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
    # self.table_name =  "admin_users"
    
    has_secure_password
    
    has_and_belongs_to_many :pages
    has_many :section_edits
    has_many :sections, through: :section_edits
    
    scope :sorted, lambda { order ("last_name , first_name") }
    
    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
    FORBIDDEN_USERNAMES = ['humptydumpty', 'babybaby', 'jacknjill', 'laloo']
    
    validates :first_name, :presence => true, :length => { :maximum => 25 }
    validates :last_name, :presence => true, :length => { :maximum => 50 }
    validates :username, :presence => true, :length => { :within => 8..25 }, :uniqueness => true
    
    
    
    # validates_presence_of :first_name
    # validates_length_of :first_name, :maximum => 25
    # validates_presence_of :last_name
    # validates_length_of :last_name, :maximum => 50
    # validates_presence_of :username
    # validates_length_of :username, :within => 8..25
    # validates_uniqueness_of :username
    
    # sexy_validations
    validates :email, :presence => true,
                      :length => { :maximum => 100 },
                      :format => { :with => EMAIL_REGEX },
                      :confirmation => true
    
    # validates_presence_of :email
    # validates_length_of :email, :maximum => 100 
    # validates_format_of :email, :with => EMAIL_REGEX
    # validates_confirmation_of :email 
    
    # Custom validations
    validate :username_is_allowed
    # validate :no_users_on_thursday
    
    private
    
    def username_is_allowed
        if FORBIDDEN_USERNAMES.include?(username)
           errors.add(:username, "has been restricted from use.") 
        end
    end
    
    def name
        "#{first_name} #{last_name}"
        # first_name + ' ' + last_name
        # [first_name, last_name].join(' ')
    end
    # def no_users_on_thursday
    #     if Time.now.wday == 4
    #         errors.add(:base, "No new users on Thursday.")
    #     end
    # end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
    
    layout 'admin'
    
    before_action :confirm_logged_in
    
    def index
        @admin_users = AdminUser.sorted
    end
    def new
        @admin_user = AdminUser.new()
    end
    def create
        @admin_user = AdminUser.new(admin_user_params)
        if @admin_user.save
            flash[:notice] = "Admin created successfully!."
            redirect_to(admin_users_path)
        else
            render "new"
        end
    end
    def edit
        @admin_user = AdminUser.find(params[:id])
    end
    def update
        @admin_user = AdminUser.find(params[:id])
        if @admin_user.update_attributes(admin_user_params)
            flash[:notice] = "Information updated successfully!."
            redirect_to(admin_users_path)
        else
            render "edit"
        end
    end
    def delete
        @admin_user = AdminUser.find(params[:id])
    end
    def destroy
        @admin_user = AdminUser.find(params[:id])
        @admin_user.destroy
        flash[:notice] = "Admin deleted successfully!."
        redirect_to(admin_users_path)
    end
    
    private
    
    def admin_user_params
        params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/delete.html.erb
<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Admin</h2>

  <%= form_for(@admin_user, :method => 'delete') do |a| %>

    <p>Are you sure you want to permanently delete this admin?</p>

    <p class="reference-name"><%= a.object.username %></p>

    <div class="form-buttons">
      <%= a.submit("Delete Admin") %>
    </div>

  <% end %>
</div>

app/views/admin_users/edit.html.erb
<%= form_for(@admin_user) do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="Subject form fields">
      <tr>
        <th>First Name</th>
        <td><%= f.text_field(:first_name) %></td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td><%= f.text_field(:last_name) %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= f.text_field(:username) %></td>
      </tr>
      <tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
        <th>Password</th>
        <td><%= f.password_field(:password) %></td>
      </tr>
    </table>
    <div class="form-buttons">
      <%= f.submit("Edit Admin") %>
    </div>
<% end %>

app/views/admin_users/index.html.erb
<div class="subjects index">
  <h2>Admin Users</h2>

  <%= link_to("<< Back to Menu", access_menu_path) %><br><br>

  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+')%>
  <%= link_to("Create New Admin", new_admin_user_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @admin_users.each do |admin| %>
    <tr>
      <td><%= admin.first_name %></td>
      <td><%= admin.last_name %></td>
      <td><%= admin.username %></td>
      <td class="center"><%= admin.email %></td>
      <td class="actions">
        <%= link_to("Edit", edit_admin_user_path(admin), :class => 'action edit') %>
        <%= link_to("Delete", delete_admin_user_path(admin), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<%= form_for(@admin_user) do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="Subject form fields">
      <tr>
        <th>First Name</th>
        <td><%= f.text_field(:first_name) %></td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td><%= f.text_field(:last_name) %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= f.text_field(:username) %></td>
      </tr>
      <tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
        <th>Password</th>
        <td><%= f.password_field(:password) %></td>
      </tr>
    </table>
    <div class="form-buttons">
      <%= f.submit("Create Admin") %>
    </div>
<% end %>